-- SORELLE katalog — 46 proizvoda i 117 varijanti pakovanja.
-- Generisano iz tabele „SORELLE_proizvodi_za_sajt_NOVA_TABELA" (list „Proizvodi za sajt").
--
-- Bezbedno je pokrenuti više puta: naziv, pakovanje i redosled se osvežavaju,
-- a CENE, POPUSTI, SLIKE i „na sajtu" se NE diraju — to su podaci iz admin panela.

BEGIN;

-- Placeholder katalog iz demo verzije sajta više ne postoji.
DELETE FROM public.products
WHERE slug IN ('hidratantna-krema', 'nocna-krema', 'serum-za-lice', 'micelarna-voda');

INSERT INTO public.products (slug, name, base_price_rsd, image_path, volume, sort_order, is_active)
VALUES
  ('pro-fiber-naked-skin', 'Pro Fiber Builder Gel — Naked Skin', 0, '', '10 g / 30 g / 50 g', 1, true),
  ('pro-fiber-silky-blush', 'Pro Fiber Builder Gel — Silky Blush', 0, '', '10 g / 30 g / 50 g', 2, true),
  ('pro-fiber-natural-harmony', 'Pro Fiber Builder Gel — Natural Harmony', 0, '', '10 g / 30 g / 50 g', 3, true),
  ('pro-fiber-cosmopolitan-pink', 'Pro Fiber Builder Gel — Cosmopolitan Pink', 0, '', '10 g / 30 g / 50 g', 4, true),
  ('pro-fiber-perfect-milky-white', 'Pro Fiber Builder Gel — Perfect Milky White', 0, '', '10 g / 30 g / 50 g', 5, true),
  ('pro-fiber-creamy-latte', 'Pro Fiber Builder Gel — Creamy Latte', 0, '', '10 g / 30 g / 50 g', 6, true),
  ('pro-fiber-angel-pink', 'Pro Fiber Builder Gel — Angel Pink', 0, '', '10 g / 30 g / 50 g', 7, true),
  ('pro-fiber-soft-milky-white', 'Pro Fiber Builder Gel — Soft Milky White', 0, '', '10 g / 30 g / 50 g', 8, true),
  ('fluid-perfect-cool-milky-white', 'Fluid Perfect Builder Gel — Cool Milky White', 0, '', '10 g / 30 g / 50 g', 9, true),
  ('fluid-perfect-crystal-ice-pink', 'Fluid Perfect Builder Gel — Crystal Ice Pink', 0, '', '10 g / 30 g / 50 g', 10, true),
  ('fluid-perfect-pink-sensational', 'Fluid Perfect Builder Gel — Pink Sensational', 0, '', '10 g / 30 g / 50 g', 11, true),
  ('fluid-perfect-cashmere-rose', 'Fluid Perfect Builder Gel — Cashmere Rose', 0, '', '10 g / 30 g / 50 g', 12, true),
  ('fluid-perfect-rich-worm-nude', 'Fluid Perfect Builder Gel — Rich Worm Nude', 0, '', '10 g / 30 g / 50 g', 13, true),
  ('fluid-perfect-rich-deep-nude', 'Fluid Perfect Builder Gel — Rich Deep Nude', 0, '', '10 g / 30 g / 50 g', 14, true),
  ('fluid-perfect-rich-cold-nude', 'Fluid Perfect Builder Gel — Rich Cold Nude', 0, '', '10 g / 30 g / 50 g', 15, true),
  ('fluid-perfect-clear', 'Fluid Perfect Builder Gel — Clear', 0, '', '10 g / 30 g / 50 g', 16, true),
  ('fluid-perfect-jogurt-banana', 'Fluid Perfect Builder Gel — Jogurt Banana', 0, '', '10 g / 30 g / 50 g', 17, true),
  ('fluid-perfect-jogurt-lavander-milk', 'Fluid Perfect Builder Gel — Jogurt Lavander Milk', 0, '', '10 g / 30 g / 50 g', 18, true),
  ('fluid-perfect-jogurt-blue-raspberry', 'Fluid Perfect Builder Gel — Jogurt Blue Raspberry', 0, '', '10 g / 30 g / 50 g', 19, true),
  ('fluid-perfect-jogurt-fresh-mint', 'Fluid Perfect Builder Gel — Jogurt Fresh Mint', 0, '', '10 g / 30 g / 50 g', 20, true),
  ('fluid-perfect-natural-perfection', 'Fluid Perfect Builder Gel — Natural Perfection', 0, '', '10 g / 30 g / 50 g', 21, true),
  ('fluid-perfect-royal-beige', 'Fluid Perfect Builder Gel — Royal Beige', 0, '', '10 g / 30 g / 50 g', 22, true),
  ('fluid-perfect-jogurt-melon-cream', 'Fluid Perfect Builder Gel — Jogurt Melon Cream', 0, '', '10 g / 30 g / 50 g', 23, true),
  ('fluid-perfect-jogurt-ice-berry-milk', 'Fluid Perfect Builder Gel — Jogurt Ice Berry Milk', 0, '', '10 g / 30 g / 50 g', 24, true),
  ('fluid-perfect-jogurt-sweet-strawberry', 'Fluid Perfect Builder Gel — Jogurt Sweet Strawberry', 0, '', '10 g / 30 g / 50 g', 25, true),
  ('rubber-base-cool-milky-white', 'Rubber Base Camouflage — Cool Milky White', 0, '', '10 ml / 15 ml', 26, true),
  ('rubber-base-crystal-ice-pink', 'Rubber Base Camouflage — Crystal Ice Pink', 0, '', '10 ml / 15 ml', 27, true),
  ('rubber-base-pink-sensational', 'Rubber Base Camouflage — Pink Sensational', 0, '', '10 ml / 15 ml', 28, true),
  ('rubber-base-cashmere-rose', 'Rubber Base Camouflage — Cashmere Rose', 0, '', '10 ml / 15 ml', 29, true),
  ('rubber-base-rich-worm-nude', 'Rubber Base Camouflage — Rich Worm Nude', 0, '', '10 ml / 15 ml', 30, true),
  ('rubber-base-rich-deep-nude', 'Rubber Base Camouflage — Rich Deep Nude', 0, '', '10 ml / 15 ml', 31, true),
  ('rubber-base-rich-cold-nude', 'Rubber Base Camouflage — Rich Cold Nude', 0, '', '10 ml / 15 ml', 32, true),
  ('rubber-base-clear', 'Rubber Base Camouflage — Clear', 0, '', '10 ml / 15 ml', 33, true),
  ('rubber-base-jogurt-banana', 'Rubber Base Camouflage — Jogurt Banana', 0, '', '10 ml / 15 ml', 34, true),
  ('rubber-base-jogurt-lavander-milk', 'Rubber Base Camouflage — Jogurt Lavander Milk', 0, '', '10 ml / 15 ml', 35, true),
  ('rubber-base-jogurt-blue-raspberry', 'Rubber Base Camouflage — Jogurt Blue Raspberry', 0, '', '10 ml / 15 ml', 36, true),
  ('rubber-base-jogurt-fresh-mint', 'Rubber Base Camouflage — Jogurt Fresh Mint', 0, '', '10 ml / 15 ml', 37, true),
  ('rubber-base-natural-perfection', 'Rubber Base Camouflage — Natural Perfection', 0, '', '10 ml / 15 ml', 38, true),
  ('rubber-base-royal-beige', 'Rubber Base Camouflage — Royal Beige', 0, '', '10 ml / 15 ml', 39, true),
  ('rubber-base-jogurt-melon-cream', 'Rubber Base Camouflage — Jogurt Melon Cream', 0, '', '10 ml / 15 ml', 40, true),
  ('rubber-base-jogurt-ice-berry-milk', 'Rubber Base Camouflage — Jogurt Ice Berry Milk', 0, '', '10 ml / 15 ml', 41, true),
  ('rubber-base-jogurt-sweet-strawberry', 'Rubber Base Camouflage — Jogurt Sweet Strawberry', 0, '', '10 ml / 15 ml', 42, true),
  ('pro-base-clear', 'Pro Base Clear', 0, '', '10 ml / 15 ml', 43, true),
  ('super-shine-top-coat', 'Super Shine Top Coat', 0, '', '10 ml / 15 ml', 44, true),
  ('effect-top-coat-milky', 'Effect Top Coat Milky', 0, '', '10 ml / 15 ml', 45, true),
  ('effect-top-coat-shimmer-vibe', 'Effect Top Coat Shimmer Vibe', 0, '', '10 ml / 15 ml', 46, true)
ON CONFLICT (slug) DO UPDATE SET
  name       = EXCLUDED.name,
  volume     = EXCLUDED.volume,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.product_variants (product_slug, variant_slug, package_label, sort_order)
VALUES
  ('pro-fiber-naked-skin', 'pro-fiber-naked-skin--10g', '10 g', 1),
  ('pro-fiber-naked-skin', 'pro-fiber-naked-skin--30g', '30 g', 2),
  ('pro-fiber-naked-skin', 'pro-fiber-naked-skin--50g', '50 g', 3),
  ('pro-fiber-silky-blush', 'pro-fiber-silky-blush--10g', '10 g', 1),
  ('pro-fiber-silky-blush', 'pro-fiber-silky-blush--30g', '30 g', 2),
  ('pro-fiber-silky-blush', 'pro-fiber-silky-blush--50g', '50 g', 3),
  ('pro-fiber-natural-harmony', 'pro-fiber-natural-harmony--10g', '10 g', 1),
  ('pro-fiber-natural-harmony', 'pro-fiber-natural-harmony--30g', '30 g', 2),
  ('pro-fiber-natural-harmony', 'pro-fiber-natural-harmony--50g', '50 g', 3),
  ('pro-fiber-cosmopolitan-pink', 'pro-fiber-cosmopolitan-pink--10g', '10 g', 1),
  ('pro-fiber-cosmopolitan-pink', 'pro-fiber-cosmopolitan-pink--30g', '30 g', 2),
  ('pro-fiber-cosmopolitan-pink', 'pro-fiber-cosmopolitan-pink--50g', '50 g', 3),
  ('pro-fiber-perfect-milky-white', 'pro-fiber-perfect-milky-white--10g', '10 g', 1),
  ('pro-fiber-perfect-milky-white', 'pro-fiber-perfect-milky-white--30g', '30 g', 2),
  ('pro-fiber-perfect-milky-white', 'pro-fiber-perfect-milky-white--50g', '50 g', 3),
  ('pro-fiber-creamy-latte', 'pro-fiber-creamy-latte--10g', '10 g', 1),
  ('pro-fiber-creamy-latte', 'pro-fiber-creamy-latte--30g', '30 g', 2),
  ('pro-fiber-creamy-latte', 'pro-fiber-creamy-latte--50g', '50 g', 3),
  ('pro-fiber-angel-pink', 'pro-fiber-angel-pink--10g', '10 g', 1),
  ('pro-fiber-angel-pink', 'pro-fiber-angel-pink--30g', '30 g', 2),
  ('pro-fiber-angel-pink', 'pro-fiber-angel-pink--50g', '50 g', 3),
  ('pro-fiber-soft-milky-white', 'pro-fiber-soft-milky-white--10g', '10 g', 1),
  ('pro-fiber-soft-milky-white', 'pro-fiber-soft-milky-white--30g', '30 g', 2),
  ('pro-fiber-soft-milky-white', 'pro-fiber-soft-milky-white--50g', '50 g', 3),
  ('fluid-perfect-cool-milky-white', 'fluid-perfect-cool-milky-white--10g', '10 g', 1),
  ('fluid-perfect-cool-milky-white', 'fluid-perfect-cool-milky-white--30g', '30 g', 2),
  ('fluid-perfect-cool-milky-white', 'fluid-perfect-cool-milky-white--50g', '50 g', 3),
  ('fluid-perfect-crystal-ice-pink', 'fluid-perfect-crystal-ice-pink--10g', '10 g', 1),
  ('fluid-perfect-crystal-ice-pink', 'fluid-perfect-crystal-ice-pink--30g', '30 g', 2),
  ('fluid-perfect-crystal-ice-pink', 'fluid-perfect-crystal-ice-pink--50g', '50 g', 3),
  ('fluid-perfect-pink-sensational', 'fluid-perfect-pink-sensational--10g', '10 g', 1),
  ('fluid-perfect-pink-sensational', 'fluid-perfect-pink-sensational--30g', '30 g', 2),
  ('fluid-perfect-pink-sensational', 'fluid-perfect-pink-sensational--50g', '50 g', 3),
  ('fluid-perfect-cashmere-rose', 'fluid-perfect-cashmere-rose--10g', '10 g', 1),
  ('fluid-perfect-cashmere-rose', 'fluid-perfect-cashmere-rose--30g', '30 g', 2),
  ('fluid-perfect-cashmere-rose', 'fluid-perfect-cashmere-rose--50g', '50 g', 3),
  ('fluid-perfect-rich-worm-nude', 'fluid-perfect-rich-worm-nude--10g', '10 g', 1),
  ('fluid-perfect-rich-worm-nude', 'fluid-perfect-rich-worm-nude--30g', '30 g', 2),
  ('fluid-perfect-rich-worm-nude', 'fluid-perfect-rich-worm-nude--50g', '50 g', 3),
  ('fluid-perfect-rich-deep-nude', 'fluid-perfect-rich-deep-nude--10g', '10 g', 1),
  ('fluid-perfect-rich-deep-nude', 'fluid-perfect-rich-deep-nude--30g', '30 g', 2),
  ('fluid-perfect-rich-deep-nude', 'fluid-perfect-rich-deep-nude--50g', '50 g', 3),
  ('fluid-perfect-rich-cold-nude', 'fluid-perfect-rich-cold-nude--10g', '10 g', 1),
  ('fluid-perfect-rich-cold-nude', 'fluid-perfect-rich-cold-nude--30g', '30 g', 2),
  ('fluid-perfect-rich-cold-nude', 'fluid-perfect-rich-cold-nude--50g', '50 g', 3),
  ('fluid-perfect-clear', 'fluid-perfect-clear--10g', '10 g', 1),
  ('fluid-perfect-clear', 'fluid-perfect-clear--30g', '30 g', 2),
  ('fluid-perfect-clear', 'fluid-perfect-clear--50g', '50 g', 3),
  ('fluid-perfect-jogurt-banana', 'fluid-perfect-jogurt-banana--10g', '10 g', 1),
  ('fluid-perfect-jogurt-banana', 'fluid-perfect-jogurt-banana--30g', '30 g', 2),
  ('fluid-perfect-jogurt-banana', 'fluid-perfect-jogurt-banana--50g', '50 g', 3),
  ('fluid-perfect-jogurt-lavander-milk', 'fluid-perfect-jogurt-lavander-milk--10g', '10 g', 1),
  ('fluid-perfect-jogurt-lavander-milk', 'fluid-perfect-jogurt-lavander-milk--30g', '30 g', 2),
  ('fluid-perfect-jogurt-lavander-milk', 'fluid-perfect-jogurt-lavander-milk--50g', '50 g', 3),
  ('fluid-perfect-jogurt-blue-raspberry', 'fluid-perfect-jogurt-blue-raspberry--10g', '10 g', 1),
  ('fluid-perfect-jogurt-blue-raspberry', 'fluid-perfect-jogurt-blue-raspberry--30g', '30 g', 2),
  ('fluid-perfect-jogurt-blue-raspberry', 'fluid-perfect-jogurt-blue-raspberry--50g', '50 g', 3),
  ('fluid-perfect-jogurt-fresh-mint', 'fluid-perfect-jogurt-fresh-mint--10g', '10 g', 1),
  ('fluid-perfect-jogurt-fresh-mint', 'fluid-perfect-jogurt-fresh-mint--30g', '30 g', 2),
  ('fluid-perfect-jogurt-fresh-mint', 'fluid-perfect-jogurt-fresh-mint--50g', '50 g', 3),
  ('fluid-perfect-natural-perfection', 'fluid-perfect-natural-perfection--10g', '10 g', 1),
  ('fluid-perfect-natural-perfection', 'fluid-perfect-natural-perfection--30g', '30 g', 2),
  ('fluid-perfect-natural-perfection', 'fluid-perfect-natural-perfection--50g', '50 g', 3),
  ('fluid-perfect-royal-beige', 'fluid-perfect-royal-beige--10g', '10 g', 1),
  ('fluid-perfect-royal-beige', 'fluid-perfect-royal-beige--30g', '30 g', 2),
  ('fluid-perfect-royal-beige', 'fluid-perfect-royal-beige--50g', '50 g', 3),
  ('fluid-perfect-jogurt-melon-cream', 'fluid-perfect-jogurt-melon-cream--10g', '10 g', 1),
  ('fluid-perfect-jogurt-melon-cream', 'fluid-perfect-jogurt-melon-cream--30g', '30 g', 2),
  ('fluid-perfect-jogurt-melon-cream', 'fluid-perfect-jogurt-melon-cream--50g', '50 g', 3),
  ('fluid-perfect-jogurt-ice-berry-milk', 'fluid-perfect-jogurt-ice-berry-milk--10g', '10 g', 1),
  ('fluid-perfect-jogurt-ice-berry-milk', 'fluid-perfect-jogurt-ice-berry-milk--30g', '30 g', 2),
  ('fluid-perfect-jogurt-ice-berry-milk', 'fluid-perfect-jogurt-ice-berry-milk--50g', '50 g', 3),
  ('fluid-perfect-jogurt-sweet-strawberry', 'fluid-perfect-jogurt-sweet-strawberry--10g', '10 g', 1),
  ('fluid-perfect-jogurt-sweet-strawberry', 'fluid-perfect-jogurt-sweet-strawberry--30g', '30 g', 2),
  ('fluid-perfect-jogurt-sweet-strawberry', 'fluid-perfect-jogurt-sweet-strawberry--50g', '50 g', 3),
  ('rubber-base-cool-milky-white', 'rubber-base-cool-milky-white--10ml', '10 ml', 1),
  ('rubber-base-cool-milky-white', 'rubber-base-cool-milky-white--15ml', '15 ml', 2),
  ('rubber-base-crystal-ice-pink', 'rubber-base-crystal-ice-pink--10ml', '10 ml', 1),
  ('rubber-base-crystal-ice-pink', 'rubber-base-crystal-ice-pink--15ml', '15 ml', 2),
  ('rubber-base-pink-sensational', 'rubber-base-pink-sensational--10ml', '10 ml', 1),
  ('rubber-base-pink-sensational', 'rubber-base-pink-sensational--15ml', '15 ml', 2),
  ('rubber-base-cashmere-rose', 'rubber-base-cashmere-rose--10ml', '10 ml', 1),
  ('rubber-base-cashmere-rose', 'rubber-base-cashmere-rose--15ml', '15 ml', 2),
  ('rubber-base-rich-worm-nude', 'rubber-base-rich-worm-nude--10ml', '10 ml', 1),
  ('rubber-base-rich-worm-nude', 'rubber-base-rich-worm-nude--15ml', '15 ml', 2),
  ('rubber-base-rich-deep-nude', 'rubber-base-rich-deep-nude--10ml', '10 ml', 1),
  ('rubber-base-rich-deep-nude', 'rubber-base-rich-deep-nude--15ml', '15 ml', 2),
  ('rubber-base-rich-cold-nude', 'rubber-base-rich-cold-nude--10ml', '10 ml', 1),
  ('rubber-base-rich-cold-nude', 'rubber-base-rich-cold-nude--15ml', '15 ml', 2),
  ('rubber-base-clear', 'rubber-base-clear--10ml', '10 ml', 1),
  ('rubber-base-clear', 'rubber-base-clear--15ml', '15 ml', 2),
  ('rubber-base-jogurt-banana', 'rubber-base-jogurt-banana--10ml', '10 ml', 1),
  ('rubber-base-jogurt-banana', 'rubber-base-jogurt-banana--15ml', '15 ml', 2),
  ('rubber-base-jogurt-lavander-milk', 'rubber-base-jogurt-lavander-milk--10ml', '10 ml', 1),
  ('rubber-base-jogurt-lavander-milk', 'rubber-base-jogurt-lavander-milk--15ml', '15 ml', 2),
  ('rubber-base-jogurt-blue-raspberry', 'rubber-base-jogurt-blue-raspberry--10ml', '10 ml', 1),
  ('rubber-base-jogurt-blue-raspberry', 'rubber-base-jogurt-blue-raspberry--15ml', '15 ml', 2),
  ('rubber-base-jogurt-fresh-mint', 'rubber-base-jogurt-fresh-mint--10ml', '10 ml', 1),
  ('rubber-base-jogurt-fresh-mint', 'rubber-base-jogurt-fresh-mint--15ml', '15 ml', 2),
  ('rubber-base-natural-perfection', 'rubber-base-natural-perfection--10ml', '10 ml', 1),
  ('rubber-base-natural-perfection', 'rubber-base-natural-perfection--15ml', '15 ml', 2),
  ('rubber-base-royal-beige', 'rubber-base-royal-beige--10ml', '10 ml', 1),
  ('rubber-base-royal-beige', 'rubber-base-royal-beige--15ml', '15 ml', 2),
  ('rubber-base-jogurt-melon-cream', 'rubber-base-jogurt-melon-cream--10ml', '10 ml', 1),
  ('rubber-base-jogurt-melon-cream', 'rubber-base-jogurt-melon-cream--15ml', '15 ml', 2),
  ('rubber-base-jogurt-ice-berry-milk', 'rubber-base-jogurt-ice-berry-milk--10ml', '10 ml', 1),
  ('rubber-base-jogurt-ice-berry-milk', 'rubber-base-jogurt-ice-berry-milk--15ml', '15 ml', 2),
  ('rubber-base-jogurt-sweet-strawberry', 'rubber-base-jogurt-sweet-strawberry--10ml', '10 ml', 1),
  ('rubber-base-jogurt-sweet-strawberry', 'rubber-base-jogurt-sweet-strawberry--15ml', '15 ml', 2),
  ('pro-base-clear', 'pro-base-clear--10ml', '10 ml', 1),
  ('pro-base-clear', 'pro-base-clear--15ml', '15 ml', 2),
  ('super-shine-top-coat', 'super-shine-top-coat--10ml', '10 ml', 1),
  ('super-shine-top-coat', 'super-shine-top-coat--15ml', '15 ml', 2),
  ('effect-top-coat-milky', 'effect-top-coat-milky--10ml', '10 ml', 1),
  ('effect-top-coat-milky', 'effect-top-coat-milky--15ml', '15 ml', 2),
  ('effect-top-coat-shimmer-vibe', 'effect-top-coat-shimmer-vibe--10ml', '10 ml', 1),
  ('effect-top-coat-shimmer-vibe', 'effect-top-coat-shimmer-vibe--15ml', '15 ml', 2)
ON CONFLICT (variant_slug) DO UPDATE SET
  product_slug  = EXCLUDED.product_slug,
  package_label = EXCLUDED.package_label,
  sort_order    = EXCLUDED.sort_order;

-- Varijante koje su nekad postojale a više nisu u tabeli.
DELETE FROM public.product_variants v
WHERE v.variant_slug NOT IN (
  'pro-fiber-naked-skin--10g',
  'pro-fiber-naked-skin--30g',
  'pro-fiber-naked-skin--50g',
  'pro-fiber-silky-blush--10g',
  'pro-fiber-silky-blush--30g',
  'pro-fiber-silky-blush--50g',
  'pro-fiber-natural-harmony--10g',
  'pro-fiber-natural-harmony--30g',
  'pro-fiber-natural-harmony--50g',
  'pro-fiber-cosmopolitan-pink--10g',
  'pro-fiber-cosmopolitan-pink--30g',
  'pro-fiber-cosmopolitan-pink--50g',
  'pro-fiber-perfect-milky-white--10g',
  'pro-fiber-perfect-milky-white--30g',
  'pro-fiber-perfect-milky-white--50g',
  'pro-fiber-creamy-latte--10g',
  'pro-fiber-creamy-latte--30g',
  'pro-fiber-creamy-latte--50g',
  'pro-fiber-angel-pink--10g',
  'pro-fiber-angel-pink--30g',
  'pro-fiber-angel-pink--50g',
  'pro-fiber-soft-milky-white--10g',
  'pro-fiber-soft-milky-white--30g',
  'pro-fiber-soft-milky-white--50g',
  'fluid-perfect-cool-milky-white--10g',
  'fluid-perfect-cool-milky-white--30g',
  'fluid-perfect-cool-milky-white--50g',
  'fluid-perfect-crystal-ice-pink--10g',
  'fluid-perfect-crystal-ice-pink--30g',
  'fluid-perfect-crystal-ice-pink--50g',
  'fluid-perfect-pink-sensational--10g',
  'fluid-perfect-pink-sensational--30g',
  'fluid-perfect-pink-sensational--50g',
  'fluid-perfect-cashmere-rose--10g',
  'fluid-perfect-cashmere-rose--30g',
  'fluid-perfect-cashmere-rose--50g',
  'fluid-perfect-rich-worm-nude--10g',
  'fluid-perfect-rich-worm-nude--30g',
  'fluid-perfect-rich-worm-nude--50g',
  'fluid-perfect-rich-deep-nude--10g',
  'fluid-perfect-rich-deep-nude--30g',
  'fluid-perfect-rich-deep-nude--50g',
  'fluid-perfect-rich-cold-nude--10g',
  'fluid-perfect-rich-cold-nude--30g',
  'fluid-perfect-rich-cold-nude--50g',
  'fluid-perfect-clear--10g',
  'fluid-perfect-clear--30g',
  'fluid-perfect-clear--50g',
  'fluid-perfect-jogurt-banana--10g',
  'fluid-perfect-jogurt-banana--30g',
  'fluid-perfect-jogurt-banana--50g',
  'fluid-perfect-jogurt-lavander-milk--10g',
  'fluid-perfect-jogurt-lavander-milk--30g',
  'fluid-perfect-jogurt-lavander-milk--50g',
  'fluid-perfect-jogurt-blue-raspberry--10g',
  'fluid-perfect-jogurt-blue-raspberry--30g',
  'fluid-perfect-jogurt-blue-raspberry--50g',
  'fluid-perfect-jogurt-fresh-mint--10g',
  'fluid-perfect-jogurt-fresh-mint--30g',
  'fluid-perfect-jogurt-fresh-mint--50g',
  'fluid-perfect-natural-perfection--10g',
  'fluid-perfect-natural-perfection--30g',
  'fluid-perfect-natural-perfection--50g',
  'fluid-perfect-royal-beige--10g',
  'fluid-perfect-royal-beige--30g',
  'fluid-perfect-royal-beige--50g',
  'fluid-perfect-jogurt-melon-cream--10g',
  'fluid-perfect-jogurt-melon-cream--30g',
  'fluid-perfect-jogurt-melon-cream--50g',
  'fluid-perfect-jogurt-ice-berry-milk--10g',
  'fluid-perfect-jogurt-ice-berry-milk--30g',
  'fluid-perfect-jogurt-ice-berry-milk--50g',
  'fluid-perfect-jogurt-sweet-strawberry--10g',
  'fluid-perfect-jogurt-sweet-strawberry--30g',
  'fluid-perfect-jogurt-sweet-strawberry--50g',
  'rubber-base-cool-milky-white--10ml',
  'rubber-base-cool-milky-white--15ml',
  'rubber-base-crystal-ice-pink--10ml',
  'rubber-base-crystal-ice-pink--15ml',
  'rubber-base-pink-sensational--10ml',
  'rubber-base-pink-sensational--15ml',
  'rubber-base-cashmere-rose--10ml',
  'rubber-base-cashmere-rose--15ml',
  'rubber-base-rich-worm-nude--10ml',
  'rubber-base-rich-worm-nude--15ml',
  'rubber-base-rich-deep-nude--10ml',
  'rubber-base-rich-deep-nude--15ml',
  'rubber-base-rich-cold-nude--10ml',
  'rubber-base-rich-cold-nude--15ml',
  'rubber-base-clear--10ml',
  'rubber-base-clear--15ml',
  'rubber-base-jogurt-banana--10ml',
  'rubber-base-jogurt-banana--15ml',
  'rubber-base-jogurt-lavander-milk--10ml',
  'rubber-base-jogurt-lavander-milk--15ml',
  'rubber-base-jogurt-blue-raspberry--10ml',
  'rubber-base-jogurt-blue-raspberry--15ml',
  'rubber-base-jogurt-fresh-mint--10ml',
  'rubber-base-jogurt-fresh-mint--15ml',
  'rubber-base-natural-perfection--10ml',
  'rubber-base-natural-perfection--15ml',
  'rubber-base-royal-beige--10ml',
  'rubber-base-royal-beige--15ml',
  'rubber-base-jogurt-melon-cream--10ml',
  'rubber-base-jogurt-melon-cream--15ml',
  'rubber-base-jogurt-ice-berry-milk--10ml',
  'rubber-base-jogurt-ice-berry-milk--15ml',
  'rubber-base-jogurt-sweet-strawberry--10ml',
  'rubber-base-jogurt-sweet-strawberry--15ml',
  'pro-base-clear--10ml',
  'pro-base-clear--15ml',
  'super-shine-top-coat--10ml',
  'super-shine-top-coat--15ml',
  'effect-top-coat-milky--10ml',
  'effect-top-coat-milky--15ml',
  'effect-top-coat-shimmer-vibe--10ml',
  'effect-top-coat-shimmer-vibe--15ml'
);

COMMIT;
