-- ═══════════════════════════════════════════════════════════════════
-- Tekstovi proizvoda u bazi — admin ih menja iz panela
--
-- Zašto: naziv, nijansa, opis, način primene i napomene o usklađenosti bili
-- su zakucani u lib/data/products.ts. Klijent nije mogao da ispravi ni slovnu
-- grešku bez izmene koda. Sada su to kolone u `products`, a katalog u kodu
-- ostaje kao rezerva kad je polje u bazi prazno.
--
-- Bezbedno je pokrenuti više puta: seed puni SAMO prazna polja, pa izmene
-- unete iz admina ostaju netaknute.
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS shade TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS features TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS how_to_use TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS formulation TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS eu_compliance TEXT NOT NULL DEFAULT '';

COMMENT ON COLUMN public.products.shade IS 'Naziv nijanse; prazno kod proizvoda bez nijansi.';
COMMENT ON COLUMN public.products.features IS 'Opis u tačkama — jedna stavka po redu u admin panelu.';
COMMENT ON COLUMN public.products.how_to_use IS 'Način primene, jedan pasus.';
COMMENT ON COLUMN public.products.formulation IS 'Oznake formulacije razdvojene znakom •.';
COMMENT ON COLUMN public.products.eu_compliance IS 'Napomena o usklađenosti sa propisima EU.';

-- Početni tekstovi iz klijentove tabele (isti kao u lib/data/products.ts).
UPDATE public.products p SET
  shade         = CASE WHEN p.shade = '' THEN c.shade ELSE p.shade END,
  features      = CASE WHEN cardinality(p.features) = 0 THEN c.features ELSE p.features END,
  how_to_use    = CASE WHEN p.how_to_use = '' THEN c.how_to_use ELSE p.how_to_use END,
  formulation   = CASE WHEN p.formulation = '' THEN c.formulation ELSE p.formulation END,
  eu_compliance = CASE WHEN p.eu_compliance = '' THEN c.eu_compliance ELSE p.eu_compliance END
FROM (VALUES
  ('pro-fiber-naked-skin', 'Pro Fiber Builder Gel', 'Naked Skin', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-silky-blush', 'Pro Fiber Builder Gel', 'Silky Blush', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-natural-harmony', 'Pro Fiber Builder Gel', 'Natural Harmony', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-cosmopolitan-pink', 'Pro Fiber Builder Gel', 'Cosmopolitan Pink', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-perfect-milky-white', 'Pro Fiber Builder Gel', 'Perfect Milky White', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-creamy-latte', 'Pro Fiber Builder Gel', 'Creamy Latte', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-angel-pink', 'Pro Fiber Builder Gel', 'Angel Pink', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-fiber-soft-milky-white', 'Pro Fiber Builder Gel', 'Soft Milky White', ARRAY['Profesionalna formula pogodna i za početnike i za iskusne tehničare', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Fiber vlakna pružaju dodatnu čvrstinu i stabilnost', 'Odličan balans fleksibilnosti i čvrstine', 'Samonivelišuća tekstura koja se lako kontroliše i ne razliva', 'Pogodan za rad na šablonima, dual tipsama i No File tehniku']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Pro Fiber Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-cool-milky-white', 'Fluid Perfect Builder Gel', 'Cool Milky White', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-crystal-ice-pink', 'Fluid Perfect Builder Gel', 'Crystal Ice Pink', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-pink-sensational', 'Fluid Perfect Builder Gel', 'Pink Sensational', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-cashmere-rose', 'Fluid Perfect Builder Gel', 'Cashmere Rose', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-rich-worm-nude', 'Fluid Perfect Builder Gel', 'Rich Worm Nude', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-rich-deep-nude', 'Fluid Perfect Builder Gel', 'Rich Deep Nude', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-rich-cold-nude', 'Fluid Perfect Builder Gel', 'Rich Cold Nude', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-clear', 'Fluid Perfect Builder Gel', 'Clear', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-banana', 'Fluid Perfect Builder Gel', 'Jogurt Banana', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-lavander-milk', 'Fluid Perfect Builder Gel', 'Jogurt Lavander Milk', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-blue-raspberry', 'Fluid Perfect Builder Gel', 'Jogurt Blue Raspberry', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-fresh-mint', 'Fluid Perfect Builder Gel', 'Jogurt Fresh Mint', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-natural-perfection', 'Fluid Perfect Builder Gel', 'Natural Perfection', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-royal-beige', 'Fluid Perfect Builder Gel', 'Royal Beige', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-melon-cream', 'Fluid Perfect Builder Gel', 'Jogurt Melon Cream', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-ice-berry-milk', 'Fluid Perfect Builder Gel', 'Jogurt Ice Berry Milk', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('fluid-perfect-jogurt-sweet-strawberry', 'Fluid Perfect Builder Gel', 'Jogurt Sweet Strawberry', ARRAY['Fluidna, samonivelišuća formula za brz i precizan rad', 'Namenjen za izlivanje, ojačavanje i korekcije noktiju', 'Ređa struktura omogućava lako raspoređivanje i glatko nivelisanje', 'Odličan izbor za tehničare koji vole brži rad uz dobru kontrolu materijala', 'Pogodan za No File tehniku', 'Može se koristiti za rad na šablonima i dual tipsama']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti Sorelle Pro Base kao preporučenu podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Fluid Perfect Builder Gel odabranom tehnikom i polimerizovati 90–120 sekundi. Završiti Sorelle završnim sjajem po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-cool-milky-white', 'Rubber Base Camouflage', 'Cool Milky White', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-crystal-ice-pink', 'Rubber Base Camouflage', 'Crystal Ice Pink', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-pink-sensational', 'Rubber Base Camouflage', 'Pink Sensational', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-cashmere-rose', 'Rubber Base Camouflage', 'Cashmere Rose', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-rich-worm-nude', 'Rubber Base Camouflage', 'Rich Worm Nude', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-rich-deep-nude', 'Rubber Base Camouflage', 'Rich Deep Nude', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-rich-cold-nude', 'Rubber Base Camouflage', 'Rich Cold Nude', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-clear', 'Rubber Base Camouflage', 'Clear', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-banana', 'Rubber Base Camouflage', 'Jogurt Banana', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-lavander-milk', 'Rubber Base Camouflage', 'Jogurt Lavander Milk', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-blue-raspberry', 'Rubber Base Camouflage', 'Jogurt Blue Raspberry', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-fresh-mint', 'Rubber Base Camouflage', 'Jogurt Fresh Mint', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-natural-perfection', 'Rubber Base Camouflage', 'Natural Perfection', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-royal-beige', 'Rubber Base Camouflage', 'Royal Beige', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-melon-cream', 'Rubber Base Camouflage', 'Jogurt Melon Cream', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-ice-berry-milk', 'Rubber Base Camouflage', 'Jogurt Ice Berry Milk', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('rubber-base-jogurt-sweet-strawberry', 'Rubber Base Camouflage', 'Jogurt Sweet Strawberry', ARRAY['Fleksibilna formula namenjena ojačavanju prirodnih noktiju', 'Posebno pogodna za kraće nokte i tehniku nivelisanja', 'Ređa, samonivelišuća struktura koja se lako raspoređuje', 'Nije namenjena za izlivanje', 'Kamuflažne nijanse daju uredan i prirodan završni izgled', 'Idealna za brzo i precizno salonsko ojačavanje noktiju']::TEXT[], 'Pripremiti i matirati nokatnu ploču i očistiti alkoholom. Naneti tanak sloj Sorelle Pro Base kao podlogu i polimerizovati 90–120 sekundi u UV/LED lampi. Zatim naneti Rubber Base tehnikom nivelisanja i polimerizovati 90–120 sekundi. Nastaviti dizajnom ili završiti Sorelle topom po izboru.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('pro-base-clear', 'Pro Base Clear', '', ARRAY['Univerzalna providna baza idealna za sve tipove noktiju', 'Obezbeđuje odlično prijanjanje uz nokatnu ploču', 'Odlična podloga za Sorelle gradivne gelove', 'Nisu potrebne dodatne pripremne tečnosti pre nanošenja', 'Može se koristiti i za ojačavanje prirodnih noktiju tehnikom nivelisanja', 'Jednostavna za rad i pogodna za početnike i profesionalce']::TEXT[], 'Kao podloga za Sorelle gradivne gelove: naneti tanak sloj Pro Base na pripremljen nokat i polimerizovati 90–120 sekundi u UV/LED lampi, zatim nastaviti odabranim Sorelle gradivnim gelom. Za ojačavanje: naneti i iznivelisati Pro Base, pa polimerizovati 90–120 sekundi.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('super-shine-top-coat', 'Super Shine Top Coat', '', ARRAY['Završni sjaj namenjen zatvaranju kompletnog dizajna', 'Odlična tekstura omogućava lako i ravnomerno nanošenje', 'Daje noktima izražen, ujednačen sjaj koji traje do korekcije', 'Završnom radu daje čist i uredan finiš']::TEXT[], 'Naneti tanak i ravnomeran sloj na završen dizajn i polimerizovati 90–120 sekundi u UV/LED lampi.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('effect-top-coat-milky', 'Effect Top Coat Milky', '', ARRAY['Efektni završni sjaj sa nežnim mlečnim efektom', 'Daje noktima mekši, ujednačen i elegantan završni izgled', 'Idealan kada želite da ublažite postojeću nijansu i dodate mlečni finiš', 'Služi za zatvaranje dizajna', 'Sjaj i efekat u jednom završnom koraku']::TEXT[], 'Naneti tanak i ravnomeran sloj preko završenog dizajna i polimerizovati 90–120 sekundi u UV/LED lampi.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode'),
  ('effect-top-coat-shimmer-vibe', 'Effect Top Coat Shimmer Vibe', '', ARRAY['Efektni završni sjaj sa nežnim shimmer/bisernim efektom', 'Daje dodatnu dimenziju i poseban finiš postojećoj nijansi', 'Može promeniti završni izgled manikira bez dodatnog dizajna', 'Služi za zatvaranje dizajna', 'Sjaj i efekat u jednom završnom koraku']::TEXT[], 'Naneti tanak i ravnomeran sloj preko završenog dizajna i polimerizovati 90–120 sekundi u UV/LED lampi.', 'HEMA Free • Di-HEMA Free • TPO Free', 'Usklađeno sa važećim propisima EU za kozmetičke proizvode')
) AS c (slug, name, shade, features, how_to_use, formulation, eu_compliance)
WHERE p.slug = c.slug;

COMMIT;
