-- ═══════════════════════════════════════════════════════════════════
-- Porudžbina: čitljiv broj, opština i dodatak adresi
--
-- Zašto:
--  1) `orders.id` je UUID — dobar kao tajni ključ za link ka PDF potvrdi,
--     ali neupotrebljiv kad kupac zove telefonom. `order_number` je kratak
--     redni broj (od 1001) koji stoji na potvrdi, u mejlu i u adminu.
--  2) Kurirske službe traže opštinu uz mesto (npr. Beograd → Zvezdara),
--     a sprat, stan i ulaz su do sada završavali u napomeni ili nigde.
--
-- Bezbedno je pokrenuti više puta.
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS order_number BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001),
  ADD COLUMN IF NOT EXISTS municipality  TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS address_extra TEXT NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_order_number
  ON public.orders (order_number);

COMMENT ON COLUMN public.orders.order_number IS
  'Redni broj porudžbine za kupca (od 1001). Stoji na PDF potvrdi i u mejlu.';
COMMENT ON COLUMN public.orders.municipality IS
  'Opština za dostavu — kurirske službe je traže uz mesto.';
COMMENT ON COLUMN public.orders.address_extra IS
  'Sprat, stan, ulaz — opciono.';

-- Pretraga u adminu sada nalazi i po broju porudžbine, opštini i dodatku adresi.
CREATE OR REPLACE FUNCTION public.search_admin_orders(
  p_query text DEFAULT NULL,
  p_status text DEFAULT NULL,
  p_limit integer DEFAULT 200,
  p_offset integer DEFAULT 0
)
RETURNS SETOF public.orders
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  q text := trim(coalesce(p_query, ''));
  tokens text[];
BEGIN
  IF auth.uid() IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'not authorized';
  END IF;

  IF q = '' THEN
    RETURN QUERY
    SELECT o.*
    FROM public.orders o
    WHERE (
      p_status IS NULL
      OR trim(p_status) = ''
      OR lower(trim(p_status)) = 'all'
      OR o.status = p_status
    )
    ORDER BY o.created_at DESC
    LIMIT greatest(1, least(p_limit, 500))
    OFFSET greatest(0, p_offset);
    RETURN;
  END IF;

  tokens := array_remove(
    regexp_split_to_array(public.normalize_search_text(q), '\s+'),
    ''
  );

  RETURN QUERY
  SELECT o.*
  FROM public.orders o
  WHERE (
    p_status IS NULL
    OR trim(p_status) = ''
    OR lower(trim(p_status)) = 'all'
    OR o.status = p_status
  )
  AND (
    SELECT bool_and(
      public.normalize_search_text(
        coalesce(o.order_number::text, '') || ' ' ||
        coalesce(o.customer_first_name, '') || ' ' ||
        coalesce(o.customer_last_name, '') || ' ' ||
        coalesce(o.customer_email, '') || ' ' ||
        coalesce(o.customer_phone, '') || ' ' ||
        o.total_rsd::text || ' ' ||
        coalesce(o.address_line, '') || ' ' ||
        coalesce(o.address_extra, '') || ' ' ||
        coalesce(o.city, '') || ' ' ||
        coalesce(o.municipality, '') || ' ' ||
        coalesce(o.postal_code, '') || ' ' ||
        coalesce(o.promo_code, '') || ' ' ||
        coalesce(o.line_items::text, '')
      ) LIKE '%' || public.normalize_search_text(t) || '%'
    )
    FROM unnest(tokens) AS t
  )
  ORDER BY o.created_at DESC
  LIMIT greatest(1, least(p_limit, 500))
  OFFSET greatest(0, p_offset);
END;
$$;

GRANT EXECUTE ON FUNCTION public.search_admin_orders(text, text, integer, integer)
  TO authenticated, service_role;

COMMIT;
